# Generated by Django 4.0 on 2024-02-02 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductPictures',
            new_name='ProductPicture',
        ),
        migrations.AlterField(
            model_name='product',
            name='state',
            field=models.CharField(choices=[('in', 'In stock'), ('na', 'Not avaible')], default='in', max_length=2, verbose_name='product state'),
        ),
    ]
